### ISSUE TITLE
IndexError: list index out of range for temperature data when updating temperature vs. strain plots

### ISSUE THREAD

**Issue by walgren** [maestrolab/SMAREACTcleaned#21]
During gradient-based optimization, the code will occasionally err out with a "list index is out of range" error. 
This may be due to the SMA solver not converging, and thus the temperature data does not exist. 

Full (ish) traceback: 
``
Traceback (most recent call last):
  File "C:\Users\pwal5\Documents\GitHub\SMAREACTcleaned\launch_GUI.py", line 177, in run_calibration
    self.optimization_error = main(
  File "C:\Users\pwal5\Documents\GitHub\SMAREACTcleaned\calibration\model_funcs\test_optimizer_v2.py", line 541, in main
    res2 = opt.minimize(
  File "C:\Users\pwal5\anaconda3\lib\site-packages\scipy\optimize\_minimize.py", line 708, in minimize
    res = _minimize_slsqp(fun, x0, args, jac, bounds,
  File "C:\Users\pwal5\anaconda3\lib\site-packages\scipy\optimize\_slsqp_py.py", line 428, in _minimize_slsqp
    fx = wrapped_fun(x)
  File "C:\Users\pwal5\anaconda3\lib\site-packages\scipy\optimize\_optimize.py", line 277, in eval
    return func(x)
  File "C:\Users\pwal5\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 267, in fun
    self._update_fun()
  File "C:\Users\pwal5\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "C:\Users\pwal5\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "C:\Users\pwal5\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "C:\Users\pwal5\Documents\GitHub\SMAREACTcleaned\calibration\model_funcs\test_optimizer_v2.py", line 323, in evaluate
    calWin.updateTempStrain(T_total, eps_model_total, i)
  File "C:\Users\pwal5\Documents\GitHub\SMAREACTcleaned\calibration_progress\create_calibration_progress_widget.py", line 167, in updateTempStrain
    self.lines[i].set_xdata(temp[i])
IndexError: list index out of range
``

**Comment by walgren** [comment]
probably fixed with a try-catch.
